cluster-create: add handler and skell to create/delete

diff --git a/ocp-benchmark b/ocp-benchmark
--- a/ocp-benchmark
+++ b/ocp-benchmark
@@ -23,9 +23,8 @@ Usage: ${0} command [options]
 
 Available commands:
 
-    create          Create a cluster.
-    destroy         Destroy a cluster.
-    install         Install all dependencies
+    cluster         Create or Destroy a cluster.
+    dependenceis    Install dependencies
     list            List current components (clusters, results, profiles, etc)
     report          Run pre-build reports based on results collected
     run             Run benchmark from a existing cluster.
@@ -33,14 +32,17 @@ Available commands:
 Global options:
     -h | --help             Show this help
     --cluster-name {name}   Name of cluster to be created. Should match with installation directory
+    --manifests             Create manifests only
+    --ignition              Create ignition files only
 
 Available options for 'list' (only):
 
     --items           List all current items.
     --item {name}     Item to list: cluster-profiles, benchmark-profiles, clusters?, results?
 
-Available options for 'create' (only):
+Available options for 'cluster' (only):
 
+    (create|destroy)    Actions to take on cluster: Create or destroy is available.
     --cluster-profile   {name}      Tell profile to provision the cluster
     --run               {run_opt}   Create a cluster and run the tests (depends on run flags)
     --kubeconfig        {path}      Creeate a like to your kubeconfig on .local/{cluster-name}/auth/kubeconfig
@@ -93,12 +95,9 @@ EOF
 # - run
 #
 
-cmd_create() {
-    echo "[create] command not implemented. Exiting..."
-}
-
-cmd_destroy() {
-    echo "[destroy] command not implemented. Exiting..."
+cmd_cluster() {
+    echo ${OPT_CLUSTER_CMD}
+    echo "[cluster] command not implemented. Exiting..."
 }
 
 cmd_install() {
@@ -117,6 +116,19 @@ cmd_run() {
     echo "[run] command not implemented. Exiting..."
 }
 
+set_defaults() {
+
+    # Workdir
+    declare -g WORKDIR="${PWD}/$(yq . config.yaml |jq -r .config.workdir)"
+    declare -g WORKDIR_CLUSTERS="${PWD}/$(yq . config.yaml |jq -r .config.workdir)/clusters"
+
+    # Installer options
+    declare -g OPT_CLUSTER_CMD=""
+    declare -g OPT_KUBECONFIG=false
+
+    # 
+}
+
 parse_opts() {
 
     CURRENT_OPTS="$@"
@@ -133,6 +145,7 @@ parse_opts() {
     fi
     eval set -- "${GETOPT_SET}"
 
+    set_defaults
     while true; do
         case "$1" in
             -h | --help         ) show_help; exit 2 ;;
@@ -148,8 +161,6 @@ parse_opts() {
     done
 
     case ${OPT_CMD} in
-        "create"    ) cmd_create ;;
-        "destroy"   ) cmd_destroy ;;
         "install"   ) cmd_install ;;
         "list"      ) cmd_list ;;
         "report"    ) cmd_report ;;
@@ -157,9 +168,68 @@ parse_opts() {
     esac
 }
 
+parse_opt_cluster() {
+
+    set_defaults
+    case ${1} in
+        "create"|"destroy") OPT_CLUSTER_CMD="${1}"; shift ;;
+        * ) echo "Create target was not found. Use one of: create|destroy"; exit 1 ;;
+    esac
+
+    CURRENT_OPTS="$@"
+    # NOTE: This requires GNU getopt.
+    # '-> On Mac OS X and FreeBSD need to be installed as: brew install gnu-getopt
+    GETOPT_SET=`getopt -n 'ocp-benchmark' \
+            -o hdcd \
+            --long debug,help,cluster-name:,cluster-profile:,kubeconfig, \
+            -- "$@"`
+
+    if [ $? != 0 ] ; then
+        echo "gnu-getopt seems not to be present. Please install it. Terminating..." >&2 ;
+        exit 1 ;
+    fi
+    eval set -- "${GETOPT_SET}"
+
+    while true; do
+        case "$1" in
+            -h | --help         ) show_help; exit 2 ;;
+            -d | --debug        ) OPT_DEBUG=true; shift ;;
+            --cluster-name      ) OPT_CLUSTER_NAME="$2" ; shift 2 ;;
+            --cluster-profile   ) OPT_CLUSTER_PROFILE="$2"; shift 2 ;;
+            --kubeconfig        ) OPT_KUBECONFIG=true; shift ;;
+            -- ) shift; break ;;
+            * ) echo "Option not found"; break ;;
+        esac
+    done
+
+    # Validations
+    if [[ -z ${OPT_CLUSTER_NAME:-} ]]; then
+        echo "ERROR: missing flag --cluster-name {name}";
+        exit 1
+    fi
+
+    if [[ ${OPT_KUBECONFIG:-} == true ]]; then
+        if [[ "${KUBECONFIG:-}x" == "x" ]]; then
+            echo "ERROR: --kubeconfig was set but KUBECONFIG environment was not found";
+            exit 1;
+        fi
+        echo "Using KUBECONFIG=${KUBECONFIG}"
+    fi
+
+    # Globals
+    declare -g CLUSTER_KUBECONFIG=${WORKDIR_CLUSTERS}/${OPT_CLUSTER_NAME}/auth/kubeconfig
+
+    source $(dirname $0)/src/cluster
+    installer_cluster_main
+}
+
 parse_cmds() {
     case ${1:-""} in
-    "create"|"destroy"|"install"|"list"|"report"|"run" ) OPT_CMD="$1"; shift; parse_opts "$@";;
+    "cluster"|"c"       ) OPT_CMD="$1"; shift; parse_opt_cluster "$@";;
+    "dependencies"|"d"  ) OPT_CMD="$1"; shift; parse_opts "$@";;
+    "list"              ) OPT_CMD="$1"; shift; parse_opts "$@";;
+    "report"            ) OPT_CMD="$1"; shift; parse_opts "$@";;
+    "run"               ) OPT_CMD="$1"; shift; parse_opts "$@";;
     *) echo "Command [${1:-}] not found"; show_help;;
     esac
 }
