Add CCO and AlibabaCloud support (#4)
* chore: removing script moved to wflow

* feat/cco: add cco profile and patchs

* fixes/cco: make installation works, rename manifest patch to hook

* chore: create alias for root bin to oco (ocp cluster orchestrator)

* feat/install-platform: supporting alibabacloud

* alibaba: add custom cco installer

* fix/config-builder: hide platform when theres no items

diff --git a/src/cluster_patchs b/src/cluster_patchs
--- a/src/cluster_patchs
+++ b/src/cluster_patchs
@@ -1,7 +1,11 @@
 #!/bin/sh
 
 #
-# Manifests Patchs
+# Cluster patchs
+#
+
+#
+# Manifests Patchs / step
 #
 
 # Patch Machine Manifest for AWS to add two block devices
@@ -49,6 +53,7 @@ EOF
   rm -rf ${tmpdir}
 }
 
+# patch MachineConfig adding extra disk to mount etcd
 patch_machineConfig_aws_mount_etcd() {
 
   # https://docs.fedoraproject.org/en-US/fedora-coreos/storage/
@@ -90,4 +95,229 @@ spec:
             [Install]
             WantedBy=local-fs.target
 EOF
+}
+
+# Run CCO as manual-STS
+# https://docs.openshift.com/container-platform/4.9/authentication/managing_cloud_provider_credentials/cco-mode-sts.html
+patch_cco_aws_sts() {
+  pushd ${CLUSTER_HOME}
+
+  local bin_oc=$(yq -r .oc_path ${CLUSTER_CFG_RENDERED})
+  local bin_installer=$(yq -r .installer_path ${CLUSTER_CFG_RENDERED})
+  local bin_ccoctl=$(yq -r .ccoctl_path ${CLUSTER_CFG_RENDERED})
+
+  # install
+  if [[ ! -x ${bin_ccoctl} ]]; then
+    echo "#> Getting CCO IMAGE"
+    CCO_IMAGE=$(${bin_oc} adm release info \
+                -a ${PULL_SECRET_PATH} \
+                --image-for='cloud-credential-operator' \
+                ${RELEASE_IMAGE})
+    echo "#> Extracting ccoctl binary"
+    ${bin_oc} image extract ${CCO_IMAGE} \
+      -a ${PULL_SECRET_PATH} \
+      --file="/usr/bin/ccoctl"
+    mv ./ccoctl ${bin_ccoctl}
+    chmod 775 ${bin_ccoctl}
+  fi
+
+  #mkdir -p ${CLUSTER_HOME}/_cco-credRequests
+  echo "#> Extracting Credential Request manifests from release"
+  ${bin_oc} adm release extract \
+    -a ${PULL_SECRET_PATH} \
+    --credentials-requests \
+    --cloud aws \
+    --to ${CLUSTER_HOME}/_cco-credRequests \
+    ${RELEASE_IMAGE}
+
+  # BZ https://bugzilla.redhat.com/show_bug.cgi?id=2035903
+  rm -vf ${CLUSTER_HOME}/_cco-credRequests/0000_30_capi-operator_00_credentials-request.yaml
+
+  local cluster_name=$(awk '/infrastructureName:/{print $2}' ${CLUSTER_HOME}/manifests/cluster-infrastructure-02-config.yml)
+  local cluster_region=$(awk '/region:/{print $2}' ${CLUSTER_HOME}/manifests/cluster-infrastructure-02-config.yml)
+
+  echo "#> Create AWS assets for manual STS: cluster=[${cluster_name}] region=[${cluster_region}]"
+  ${bin_ccoctl} aws create-all \
+    --name=${cluster_name} \
+    --region=${cluster_region} \
+    --credentials-requests-dir=${CLUSTER_HOME}/_cco-credRequests \
+    --output-dir=${CLUSTER_HOME}/_cco-manifests
+
+  echo "#> Copying manifests to install dir."
+  cp -v ${CLUSTER_HOME}/_cco-manifests/manifests/* ${CLUSTER_HOME}/manifests/
+  cp -av ${CLUSTER_HOME}/_cco-manifests/tls ${CLUSTER_HOME}/
+
+  popd
+}
+
+# Patch CCO S3 bucket to use restrictive policy
+patch_cco_aws_sts_s3_restrict() {
+
+  local bucket_name=$(awk '/serviceAccountIssuer:/{print$2}' ${CLUSTER_HOME}/_cco-manifests/manifests/cluster-authentication-02-config.yaml |awk -F'//' '{print$2}' |awk -F'.' '{print$1}')
+  local policy_file="${CLUSTER_HOME}/_cco-bucket-policy.json"
+
+  echo "#cco path> Modifying bucket ${bucket_name} to more restrictive policies"
+  cat << EOF > ${policy_file}
+{
+    "Version": "2012-10-17",
+    "Id": "SourceIP",
+    "Statement": [
+        {
+            "Sid": "SourceIP",
+            "Effect": "Allow",
+            "Principal": "*",
+            "Action": "s3:Get*",
+            "Resource": [
+                "arn:aws:s3:::${bucket_name}",
+                "arn:aws:s3:::${bucket_name}/*"
+            ],
+            "Condition": {
+                "IpAddress": {
+                    "aws:SourceIp": "10.0.0.0/8"
+                }
+            }
+        }
+    ]
+}
+EOF
+
+  echo "#cco patch>> Creating bucket policy: "
+  cat ${policy_file}
+  aws s3api put-bucket-policy \
+    --bucket ${bucket_name} \
+    --policy file://${policy_file}
+
+  BLOCK_CFG="BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
+  echo "#cco patch>> Removing public access config: ${BLOCK_CFG}"
+  aws s3api put-public-access-block \
+    --bucket ${bucket_name} \
+    --public-access-block-configuration ${BLOCK_CFG}
+}
+
+# patch_s3_nobucket() {
+
+#   local bucket_name=$(awk '/serviceAccountIssuer:/{print$2}' ${CLUSTER_HOME}/_cco-manifests/manifests/cluster-authentication-02-config.yaml |awk -F'//' '{print$2}' |awk -F'.' '{print$1}')
+
+#   echo "#> Deleting bucket ${bucket_name} objects"
+#   aws s3 rm s3://${bucket_name} --recursive
+
+#   echo "#> Deleting bucket ${bucket_name}"
+#   aws s3api delete-bucket \
+#     --bucket ${bucket_name}
+# }
+
+cluster_hook_preserve_bootstrap() {
+  export OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP=true
+  #exit 1
+}
+
+# WIP
+# (lab) Manifest Hook to create OIDC with CloudFront
+patch_cco_aws_sts_s3_restrict_cloudfront() {
+  local bucket_name=$(awk '/serviceAccountIssuer:/{print$2}' ${CLUSTER_HOME}/_cco-manifests/manifests/cluster-authentication-02-config.yaml |awk -F'//' '{print$2}' |awk -F'.' '{print$1}')
+  local policy_file="${CLUSTER_HOME}/_cco-bucket-policy.json"
+
+  # Create CF distribution
+  # https://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-cloud-front-origin-access-identity.html
+  CFN_ID=$(aws cloudfront create-cloud-front-origin-access-identity \
+    --cloud-front-origin-access-identity-config \
+      CallerReference="cfn-identity-oidc-${cluster_name}",Comment="CloudFront identity for cluster ${cluster_name}" \
+      |jq .CloudFrontOriginAccessIdentity.Id)
+
+  aws cloudfront create-distribution --generate-cli-skeleton
+
+  echo "#cco path> CDN config to host OIDC ${bucket_name} "
+  cat << EOF > ${policy_file}
+TBD
+EOF
+
+  echo "#cco patch>> Creating bucket policy: "
+  cat ${policy_file}
+  aws s3api put-bucket-policy \
+    --bucket ${bucket_name} \
+    --policy file://${policy_file}
+
+  BLOCK_CFG="BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"
+  echo "#cco patch>> Removing public access config: ${BLOCK_CFG}"
+  aws s3api put-public-access-block \
+    --bucket ${bucket_name} \
+    --public-access-block-configuration ${BLOCK_CFG}
+}
+
+# Hook (after manifest) to create user for CCO.
+# https://docs.openshift.com/container-platform/4.9/authentication/managing_cloud_provider_credentials/cco-mode-sts.html
+hook_cco_alicloud_user_create() {
+  pushd ${CLUSTER_HOME}
+
+  local bin_oc=$(yq -r .oc_path ${CLUSTER_CFG_RENDERED})
+  local bin_installer=$(yq -r .installer_path ${CLUSTER_CFG_RENDERED})
+  local bin_ccoctl=$(yq -r .ccoctl_path ${CLUSTER_CFG_RENDERED})
+  local cloud_name="alibabacloud"
+
+  # install
+  if [[ ! -x ${bin_ccoctl} ]]; then
+    echo "#> Getting CCO IMAGE"
+    CCO_IMAGE=$(${bin_oc} adm release info \
+                -a ${PULL_SECRET_PATH} \
+                --image-for='cloud-credential-operator' \
+                ${RELEASE_IMAGE})
+    echo "#> Extracting ccoctl binary"
+    ${bin_oc} image extract ${CCO_IMAGE} \
+      -a ${PULL_SECRET_PATH} \
+      --file="/usr/bin/ccoctl"
+    mv ./ccoctl ${bin_ccoctl}
+    chmod 775 ${bin_ccoctl}
+  fi
+
+  #mkdir -p ${CLUSTER_HOME}/_cco-credRequests
+  echo "#> Extracting Credential Request manifests from release"
+  ${bin_oc} adm release extract \
+    --loglevel ${OC_OPTION_LOGLEVEL} \
+    -a ${PULL_SECRET_PATH} \
+    --credentials-requests \
+    --cloud ${cloud_name} \
+    --to ${CLUSTER_HOME}/_cco-credRequests \
+    ${RELEASE_IMAGE}
+  #cp -rvf ${CLUSTER_HOME}_backup/_cco-credRequests ${CLUSTER_HOME}/_cco-credRequests
+  #rm -rvf ${CLUSTER_HOME}/_cco-manifests
+
+  # BZ https://bugzilla.redhat.com/show_bug.cgi?id=2035903
+  rm -vf ${CLUSTER_HOME}/_cco-credRequests/0000_30_capi-operator_00_credentials-request.yaml
+
+  local cluster_name=$(awk '/infrastructureName:/{print $2}' ${CLUSTER_HOME}/manifests/cluster-infrastructure-02-config.yml)
+  local cluster_region=$(awk '/region:/{print $2}' ${CLUSTER_HOME}/manifests/cluster-infrastructure-02-config.yml)
+
+  echo "#> Create AlibabaCloud users for CCO: cluster=[${cluster_name}] region=[${cluster_region}]"
+  ${bin_ccoctl} ${cloud_name} create-ram-users \
+    --name=${cluster_name} \
+    --region=${cluster_region} \
+    --credentials-requests-dir=${CLUSTER_HOME}/_cco-credRequests \
+    --output-dir=${CLUSTER_HOME}/_cco-manifests
+
+  echo "#> Copying manifests to install dir."
+  cp -v ${CLUSTER_HOME}/_cco-manifests/manifests/* ${CLUSTER_HOME}/manifests/
+
+  popd
+}
+
+cluster_hook_cco_alicloud_user_delete() {
+  pushd ${CLUSTER_HOME}
+
+  local bin_ccoctl=$(yq -r .ccoctl_path ${CLUSTER_CFG_RENDERED})
+  local cloud_name="alibabacloud"
+  local before_meta_file="${CLUSTER_HOME}/.metadata.json"
+
+  if [[  ! -f ${before_meta_file} ]]; then
+    echo "hook [cluster_hook_cco_alicloud_user_delete] file not found: ${before_meta_file}"
+    return
+  fi
+  
+  local cluster_name=$(yq -r .infraID ${before_meta_file})
+  local cluster_region=$(yq -r .alibabacloud.region ${before_meta_file})
+
+  echo "#> Create AlibabaCloud users for CCO: cluster=[${cluster_name}] region=[${cluster_region}]"
+  ${bin_ccoctl} ${cloud_name} delete-ram-users \
+    --name=${cluster_name} \
+    --region=${cluster_region} 
+  popd
 }
